name: deploy-toy-website-end-to-end
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

parameters:
- name: customerPrefix
  type: string
  default: sgov
- name: workload
  type: string
  default: ews

jobs:

  # Build the application and database.
  build:
    uses: ./.github/workflows/build.yml

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy to the test environment.
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    needs: [build, lint]
    with:
      customerPrefix: ${{ parameters.customerPrefix }}
      workload: ${{ parameters.workload }}
      environment: test
      resourceGroupName: rg-sgov-ews-test-01-web
      reviewApiUrl: https://sandbox.contoso.com/reviews
      sqlServerAdministratorLogin: TestToyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs:
    - lint
    - build
    - deploy-test
    with:
      environment: prod
      resourceGroupName: rg-sgov-ews-prod-01-web
      reviewApiUrl: https://api.contoso.com/reviews
      sqlServerAdministratorLogin: ToyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_PRODUCTION }}

